feat: добавлен функционал по добавлению, обновлению и удалению режисс…
Ivan-Mol/java-filmorate pull request #14
Opened 2023-03-31 13:51 UTC by Fenris06

…ера фильм

fix: в классе FilmDbStorage HashMap заменена на LikedListHashMap
feat: добавлена сортирока фильмов режиссера по году и по дате

2023-03-31 14:45 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        //log.debug("received DELETE /films/{filmId} ", filmId);
А зачем тут коммент?

2023-03-31 14:51 UTC, Cheshire-Cat74 approved these changes

2023-03-31 14:51 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +import org.springframework.web.bind.annotation.*;
Я бы развернула импорты

2023-03-31 14:51 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +import lombok.*;
Я бы развернула импорты, чтобы лишние не подтягивать

2023-03-31 14:51 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +import java.util.*;
Я бы развернула импорты

2023-03-31 15:39 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        //log.debug("received DELETE /films/{filmId} ", filmId);
Идея отказывалась делать коммит ссылаясь на кокой-то аргумент в этом логе. Я так понимаю что из за {filmId} этого.

2023-04-01 21:06 UTC, Ivan-Mol requested changes
Отличная работа, единственное что есть идеи как можно улучшить нэйминг методов)

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void addDirector(List<Director> director) {
Я бы назвал `addDirectors`

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/FilmStorage.java
> +    List<Film> getSortDirectorFilms(Long directorId, String sort);
Предложил бы использовать название `getSortedFilmsByDirector`

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +                throw new NotFoundException("This sort type is not supported");
Мне кажется больше подходит `ValidationException`

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/DirectorStorage.java
> +    void addFilmDirector(Film film);
Также кажется будет понятнее если назвать `replaceFilmDirectors` по аналогии с жанрами

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/DirectorStorage.java
> +    Map<Long, List<Director>> getFilmDirectors(List<Long> filmIds);
Может стоит так назвать? `getDirectorsByFilmIds`

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void addDirectorToBd(Film film) {
Можно назвать также как метод в сторадже, после переименования метода в сторадже :)

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public List<Film> getListDirectors(List<Film> films) {
`getFilmsWithDirectors`

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public Film getDirector(Film film) {
Метод выше делает то же самое. Может использовать только его?

2023-04-01 21:06 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setId(film.getId());
А что делает эта строчка?

2023-04-01 21:26 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setId(film.getId());
Она лишняя. Убрал

2023-04-01 21:28 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void addDirector(List<Director> director) {
Исправил

2023-04-01 21:30 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/FilmStorage.java
> +    List<Film> getSortDirectorFilms(Long directorId, String sort);
Исправил

2023-04-01 21:31 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +                throw new NotFoundException("This sort type is not supported");
Исправил

2023-04-01 21:34 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/DirectorStorage.java
> +    void addFilmDirector(Film film);
Исправил

2023-04-01 21:35 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/DirectorStorage.java
> +    Map<Long, List<Director>> getFilmDirectors(List<Long> filmIds);
Исправил

2023-04-01 21:36 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void addDirectorToBd(Film film) {
Сделал

2023-04-01 21:37 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public List<Film> getListDirectors(List<Film> films) {
Исправил

2023-04-01 22:14 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public Film getDirector(Film film) {
Поправил

2023-04-02 08:27 UTC, Ivan-Mol approved these changes
Отлично!

2023-04-02 08:27 UTC, merged