фича: отзывы.
Ivan-Mol/java-filmorate pull request #15
Opened 2023-04-01 11:11 UTC by Xoroma

2023-04-01 23:54 UTC, villidilli requested changes
Много комментов по чек-стайлу , в большей мере из-за них поставил Request changes

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
Может не пройти code style, предлагаю:
1. Удалить строку 16, т.к. между началом тела класса и полем не должно быть отступов
2. Удалить 18-20, либо хотя бы 20, т.к. между комментарием и след.методом и полем не должно быть пустых строк, а вообще на мой взгляд комментарии тут излишни, так как по названию класса понятно что речь о контроллере работающем с отзывами + есть путь до эндпоинтов по которым понятно какое действие обрабатывает метод

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    }
лишняя строка (39)

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
53-54, аналогичное предложение , как в стр.20

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
Роман, рекомендую добавить логирование срабатывания метода в контроллере (первой строкой тела метода), чтобы при выбросе исключения можно было понять какой метод его сгенерировал
Я обычно делать log.debug("/methodName")

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful;
Проверь пожалуйста, может ли быть поле useful быть Null
если да, то лучше использовать @NoArgsConstructor, иначе входящий объект не будет создан, т.к. будет ждать передаваемое в это поле значение

И на мой взгляд не хватает этому полю аннотации @JsonIgnore, так как если верно понял задание, то рейтинг полезности рассчитывается на основании лайков отзыва, тем самым это поле является расчетным

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int reviewId;
Рекомендую добавить аннотацию @Positive , чтобы нельзя было присвоить отрицательное значение или 0 
@Positive and @PositiveOrZero apply to numeric values and validate that they are strictly positive, or positive including 0.
https://www.baeldung.com/javax-validation#:~:text=%40Positive%20and%20%40PositiveOrZero%20apply%20to%20numeric%20values%20and%20validate%20that%20they%20are%20strictly%20positive%2C%20or%20positive%20including%200.

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private final Integer userId;
На мой взгляд финализация полей излишня, так как при получении запроса у тебя формируется всегда новый экземпляр класса

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @JsonProperty("isPositive")
Судя по документации @JsonProperty необходимо использовать когда в json "прилетает" поле с не идентичным названием, т.к. эта аннотация устанавливает как бы сопоставление у тебя оба "имени" идентичны, поэтому считаю, что аннотация тут излишня

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
Рекомендую добавить логирования для каждого метода, чтобы понять какой метод выбросил исключение

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +
стр.46 лишняя

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +public class ReviewDbStorage implements ReviewStorage {
На мой взгляд лучше заменить  @Component на @Repository, так как @Repositiry более конкретно укажет спрингу что это дао класс работающий к БД, а компонент - это более общая аннотация, применимая ко всем классам, которым необходимо создавать бин

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
стр.32 пробел не требуется

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
Рекомендую добавить логирования для методов, что они сработали, так намного проще отслеживать путь выброса исключения

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
41- лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                    String.format("Ошибка при получении: отзыв с id=%d не найден.", reviewId));
Можно обойти подстановкой, мой ревьюер говорил что это более предпочтительно, тем самым String.format не нужно вызывать 
throw new NotFoundException("Ошибка при получении: отзыв с id={} Не найден.", reviewId)

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
51 - лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                .sorted(Comparator.comparing(Review::getUseful).reversed())
Мне кажется лучше передать сортировку на сторону БД, добавив в запрос ORDER BY

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                .limit(count)
лимит и сортировку можно передать на сторону БД

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        } catch (DataAccessException e) {
Охватывает ли это исключение случай если передать в метод Null ?

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +    private void assertReviewExists(int reviewId) {
аналогично методу выше

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +    public Review addReview(Review review) {
Не знаю что проверяет тест на код стайл у ЯПа, но по код стайлу, тут много лишних строк

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        } else throw new RuntimeException("Ошибка: отзыв не был добавлен.");
На усмотрение @Ivan-Mol , не уверен что тут стоит бросать RTE

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
Лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/resources/schema.sql
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            existingReview = jdbcTemplate.queryForObject(sql, new ReviewMapper(), id);
Егор говорил, что мы рассматриваем всегда ситуацию когда нам в запрос приходит всегда существующий айдишник, поэтому технически можно отказаться от проверок на существование отзывы в базе

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
можно отказать от string format в пользу подстановки, которую ты делал в контроллере

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: лайк к отзыву с id=%d не найден.", reviewId));
на мой взгляд тут не нужно бросать исключения, если его не было в базе , то и бог с ним))) status =200 )))

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
Лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +
лишняя строка

2023-04-01 23:54 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            String sqlQuery = "SELECT (SELECT COUNT(review_id) FROM review_like_dislike WHERE is_like = true AND review_id = ?)" +
на мой взгляд лучше вынести в отдельный метод расчет полезности

2023-04-02 09:54 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.debug("Добавлен новый фильм: {}");
Тут кажется опечатка)

2023-04-02 09:54 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +public class ReviewDbStorage implements ReviewStorage {
Более правильно, да, @repository, видимо, но у нас так сложилось что везде @component, предложил бы его оставить для единообразия

2023-04-02 09:54 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                    String.format("Ошибка при получении: отзыв с id=%d не найден.", reviewId));
Это вроде только с логами так работает

2023-04-02 09:54 UTC, Ivan-Mol commented on src/main/resources/schema.sql
> +    is_like   BOOLEAN,
Лучше чтобы оно не было null(добавить NOT NULL)

2023-04-02 09:54 UTC, Ivan-Mol commented on src/main/resources/schema.sql
> +    PRIMARY KEY (review_id, user_id, is_like)
Стоит использовать PRIMARY KEY (review_id, user_id) иначе мы можем добавить и лайк и дизлайк от одного пользователя для одного фильма

2023-04-02 10:46 UTC, Ivan-Mol reviewed
Немного дополнил ревью

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful;
Кажется этого поля вообще не должно быть.

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public boolean isPositive() {
У нас же есть уже аннотация @Getter

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            review = jdbcTemplate.queryForObject(sqlQuery, new ReviewMapper(), reviewId);
Можно вынести маппер в поле чтоб каждый раз его не создавать

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        assertFilmExists(review.getFilmId());
Стоит перенести проверки фильма и изюра на уровень сервиса и использовать уже существующие.

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        return getReviewById(num.intValue());
Лучше просто вернуть переданное ревью с просетенным айдишником, чтобы лишний раз не ходить в базу.

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        } else throw new RuntimeException("Ошибка: отзыв не был добавлен.");
Другие два эксепшена не подходят, пусть будет rte

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        try {
Стоит просто вызывать getReviewById и он сам выбросит нотфаундэксепшн если ревью нет.

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: лайк к отзыву с id=%d не найден.", reviewId));
Зависит от того что ждут тесты видимо)

2023-04-02 10:46 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            usefulness = jdbcTemplate.queryForObject(sqlQuery, Integer.class, reviewId, reviewId);
Метод mapRow вызывается для каждого ревью. Внутри него не должно быть запросов в базу, полезность должна расчитываться там где используется сам маппер а не внутри него.

2023-04-02 12:36 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
Вприныпе у меня итак логируется и по описанию понятен метод. Получается двойное логирование в большинстве методов. Добавил, но не уверен, что правильно оставлять так.

2023-04-02 13:05 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful;
В тестах (и в ТЗ) проверки на нулл нет, поэтому не могу ответить определенно.   Насчет джсонигнор:  я возвращаю это плое  в ответе, поэтому не могу проигноровать.

2023-04-02 13:17 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int reviewId;
В запросе мне это поле не приходит. Я его генерируею keyHolderom, поэтому в него нельзя положить ничего извне. Кроме того, тесты падают, если добавить эту валидацию(вероятно не проходит нулл).

2023-04-02 13:27 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
Кажется в моем случае излишне, т.к методы не содержат никакой логики и  просто пробрасываются.

2023-04-02 13:31 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +public class ReviewDbStorage implements ReviewStorage {
Согласен, но у Ивана был именно @component в соседних классах, дабы не нарушать ансамбль исплозовал его. Но кажется вернее все таки Repository.

2023-04-02 13:40 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                    String.format("Ошибка при получении: отзыв с id=%d не найден.", reviewId));
Только с логами.

2023-04-02 13:49 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                .sorted(Comparator.comparing(Review::getUseful).reversed())
useFul вычисляется в маппере, а не хранится в таблице.  Сейчас не могу представить, как это красиво переделать. Направьте плиз.

2023-04-02 13:50 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                .limit(count)
Коммент на замечание выше.

2023-04-02 14:08 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        } catch (DataAccessException e) {
Насколько я понимаю, охватывает. Но можно использовать EmptyResultDataAccessException.

2023-04-02 14:13 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +    public Review addReview(Review review) {
А какой код стайл ты имеешь ввиду? Кажется иногда лучше оставлять воздух для пущей читабельности.

2023-04-02 14:19 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            existingReview = jdbcTemplate.queryForObject(sql, new ReviewMapper(), id);
Ясно. Но если уже реализовано, пусть будет.

2023-04-02 14:20 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
Вероятно только в логах так можно.

2023-04-02 14:24 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: лайк к отзыву с id=%d не найден.", reviewId));
Некая обратная связь.

2023-04-02 14:29 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            String sqlQuery = "SELECT (SELECT COUNT(review_id) FROM review_like_dislike WHERE is_like = true AND review_id = ?)" +
Вероятно так кажется из-за громостского запроса. Во внутреннем классе как-то не по-себе добавлять доп методы.

2023-04-02 14:35 UTC, Xoroma commented on src/main/resources/schema.sql
> +    PRIMARY KEY (review_id, user_id, is_like)
Спасибо, хорошее замечание.

2023-04-02 15:13 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        assertFilmExists(review.getFilmId());
Напиши подробнее как ты это видишь плиз.  Просто это будет тоже обращение к БД, а в сервисе вроде как не приветсвуется. Или я не верно понял?

2023-04-02 17:25 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            usefulness = jdbcTemplate.queryForObject(sqlQuery, Integer.class, reviewId, reviewId);
Хотя поле может быть нулл, кажется объект лучше собирать внутри маппера. Есть какая то ссылка, где про это почитать?

2023-04-02 21:42 UTC, villidilli reviewed
Роман, спасибо за исправления!
На мой взгляд остался критичный один момент связанный с отправкой запросов из маппера, то остальному могу заапрувить, т.к. не сильно критично

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
Роман, а это не двойное логирование, одно логирование отвечает за отображение точки старта метода, а твоё за результат. Если до твоего логирования произойдет ошибка, нужно будет "ползать" дебагом в поисках метода откуда он появилась, а так ты будет видеть последовательность вызовов методов в консоли и сразу поймёшь на каком методе упало приложение
Спасибо, что сделал!

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int reviewId;
Ок, если тесты падают, тогда вопросов нет

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful;
![image](https://user-images.githubusercontent.com/99210453/229378138-2b7e261e-6f1d-4e9d-9f55-641486b4af93.png)
![image](https://user-images.githubusercontent.com/99210453/229378154-55071d4e-e9d2-4a57-84df-063064f0cb3a.png)

Два скрина с моего проекта (первый pojo, второй body ответа на запрос). @JsonIgnore действительно может при сериализации "убить" поле, но если ты не обрабатываешь ResultSet вручную. В большей мере предложил "попробовать" защитить это поле от входящих данных. Если по тестам проблем нет, то "ок"

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
ок, соглашусь с твоей логикой

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +public class ReviewDbStorage implements ReviewStorage {
ОК, я не против
Не изучал досконально проект Ивана
Согласен , что лучше "стиль" поддерживать единый для удобства читабельности

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                    String.format("Ошибка при получении: отзыв с id=%d не найден.", reviewId));
загуглил, был не прав, извиняюсь

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                .sorted(Comparator.comparing(Review::getUseful).reversed())
Роман, если я правильно понял ТЗ то рейтинг отзыва = разнице лайков и дизлайков
Поля типа булево имеют представление как false\true, так и 1\0 , если ты их просто суммируешь, программа сама подставит вместо true - единицу, а вместо false = ноль

согласно твоего schema.sql запрос будет выглядеть так
![image](https://user-images.githubusercontent.com/99210453/229379661-420f43c5-ea69-4a94-839c-b830f0509276.png)

результат так: 
![image](https://user-images.githubusercontent.com/99210453/229379675-66d2a2e7-6b72-4d97-a081-a0fc84d69b73.png)


содержание таблиц примера: 
![image](https://user-images.githubusercontent.com/99210453/229379684-02150832-a12e-481a-be88-ec6841654516.png)
![image](https://user-images.githubusercontent.com/99210453/229379689-e77f3c5d-976e-4697-a5e7-c93a8e7307f4.png)


и кстати  в маппер не очень хорошо производить запросы, так как всё что написано в теле маппера, будет срабатывать на каждой строке resultSet , тем самым количество запросов к базе будет = количеству строк в result set, а как говорил ревьюер, то подключения к базе должно быть минимум, т.к. это сильно загружает её

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                .limit(count)
Написал в комменте выше код примера запроса с ORDER BY и LIMIT

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +    public Review addReview(Review review) {
да, это тоже важно, просто данные методы довольно просты по логике и множественные пробелы избыточны 
мой ревьюер отучал меня от этого где-то с 3-его спринта отправляя читать code convention и другие ресурсы на тему код стайла

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
согласен, выше отписался, моя упущение, сори

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            String sqlQuery = "SELECT (SELECT COUNT(review_id) FROM review_like_dislike WHERE is_like = true AND review_id = ?)" +
в большей мере это разделение 2х операций на отдельные методы, маппер собирает объект,  отдельный метод высчитывает рейтинг
Но тут наверное даже больше вопрос в том, что зачем маппер считает рейтинг внутри себя? вчера под утро, когда ревьюил упустил этот момент. Проблема в том, что если отправлять в маппере запросы к базе, то сильно нагружаешь её , т.к. для примера у тебя в resultSet придёт 1 млн строк, тем самым ты породишь 1 млн запросов к базе ... не есть гуд ... Полезность можно рассчитать сразу на уровне БД, выше приводил пример запроса

2023-04-02 21:42 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            usefulness = jdbcTemplate.queryForObject(sqlQuery, Integer.class, reviewId, reviewId);
Мне кажется Иван имел ввиду то, что я описал выше в причине по которой лучше не отправлять из маппера запросы. А сам объект, ты прав, собирается в маппере. Если не удаётся сразу получить RS с необходимыми полями, тогда второй запрос на получение нужно делать из метода где используется маппер. Ресурс не подскажу, но эта тема поднималась где-то на 11 спринте, то ли от ревьюеров, то ли в пачке, то ли от Егора ....

2023-04-03 07:25 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +    public Review addReview(Review review) {
С пробелами согласен. А вот про строки вопрос. Средства реaформатирования кода ИДЕИ оставляют пустые строки.

2023-04-04 12:00 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(
Здесь получается ты перехватываешь исключение которое формирует база другим исключением. Так делать не стоит так, как у базы данных есть свои исключения, и получается не понятно из-за чего произошла ошибка. Так же  queryForObject в случаи отсутствия элемента в базе выкинет свое исключение. Предлагаю в данном методе заменить queryForObject на  query и просто брать через get(0) первый элемент списка и если его нет то выбрасывать исключение NotFoundException.

2023-04-04 12:00 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new ValidationException("Ошибка при добавлении лайка/дизлайка: лайк/дизлайк уже существует.");
Тоже получается прихватываешь исключение базы другим исключением.

2023-04-04 12:00 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
Если сделать как рекомендовал в методе getReviewById можно будет избавится от блока try и делать проверку в сервисе через запроc по id.

2023-04-04 12:00 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertFilmExists");
Этот метод есть в FilmServis. Лучше его переиспользовать в ReviewService через  инжект FilmService/

2023-04-04 12:00 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertUserExists");
Аналогично. Метод есть в  USerService.

2023-04-04 12:00 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertReviewExists");
Получается у тебя уже есть метод по получению реью по id. Его можно использовать для проверки наличия юзера в базе. Поэтому этот метод можно убрать. И заиспользовать getReviewById . А еще лучше сделать это через сервер.

2023-04-04 12:00 UTC, Fenris06 commented on src/main/resources/schema.sql
> +);
Прикольная константа. А можешь объяснить как она работает и зачем он. Мне будет полезно на будущее.

2023-04-04 12:01 UTC, Fenris06 commented
В целом ты молодец. Классная работа. Но думаю лучше проверки поправить.

2023-04-04 12:16 UTC, Ivan-Mol requested changes

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.debug("Добавлен новый отзыв");
Логи, как понял, для себя дублировали, для удобства?) Кириллицу в коде лучше не использовать)

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotBlank(message = "Содержание отзыва не может быть пустым.")
Кириллицу также лучше не использовать

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void addValueToReview(int reviewId, int userId, boolean isLike) {
Может для обоих методов addLikeOrDisToReview?

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void removeValueFromReview(int reviewId, int userId, boolean isLike) {
removeLikeOrDisFromReview?

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +                    String.format("Ошибка при получении: отзыв с id=%d не найден.", reviewId));
Опять кириллица

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        assertFilmExists(review.getFilmId());
Посмотри на метод checkUserExists в FilmService и где он используется. Он просто вызывает метод гет в котором проверка на существование и если что,  бросает NotFoundException. У тебя можно сделать также, без написания еще раз похожих методов, потому что они уже есть в стораджах фильмов и юзеров

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            Integer usefulness;
Остался видимо с прошлой реализации)

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        assertReviewExists(reviewId);
Также проверяем на уровне сервиса

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        assertUserExists(userId);
Тоже выше проверяем

2023-04-04 12:16 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            existingReview = jdbcTemplate.queryForObject(sql, reviewMapper, id);
А если просто вызвать выше в ReviewService метод getReviewById перед этим методом? Понадобиться эта проверка?)

2023-04-04 18:16 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(
Кажется можно просто добавить  e.getMessage().  Насчет query  не уверен...forObject как раз для одного объекта.  
![image](https://user-images.githubusercontent.com/113625703/229869875-73eb780a-cb35-448c-a874-338420d4eb95.png)

2023-04-04 18:21 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
Пока не могу найти аргументов в пользу queryForObject, но как то лист создававть кажется излишне. Как другие думают?

2023-04-04 18:24 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertFilmExists");
Он там из юзерстораджа тащит, а у меня из базы надо переоопределять тогда.  Полагаю нет смысла.

2023-04-04 18:27 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertFilmExists");
Надо подумать. Это все таки ДАО класс, а сервисный метод тогда лучше в сервисе использовать.

2023-04-04 18:30 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertReviewExists");
Через сервер не понял немного -то как? ассертРевью удобен тем, что ничего не возвращает.

2023-04-04 18:32 UTC, Xoroma commented on src/main/resources/schema.sql
> +);
Задумка на подобии обычного НОТБланка, т.е не нулл, но и не пустой.

2023-04-04 18:43 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            Integer usefulness;
Удалил

2023-04-04 18:53 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            existingReview = jdbcTemplate.queryForObject(sql, reviewMapper, id);
Просится ассерРевью(), но задумка была в том, чтобы добавить инфу, что именно при апдейте.

2023-04-04 19:32 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertFilmExists");
Кроме того там чек методы приватные.

2023-04-04 19:32 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertUserExists");
Выше

2023-04-04 19:59 UTC, Xoroma commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new ValidationException("Ошибка при добавлении лайка/дизлайка: лайк/дизлайк уже существует.");
Поменял.

2023-04-05 07:20 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(
Артём, не соглашусь, "перепроброс" исключений нормальная практика, т.к. ты выбрасываешь кастомное исключение, единственное в таких случаях создают отдельный класс аля "CustomResponceAnswer" и возвращают его в теле ответа. Данный класс в ответе может содержать e.getMessage()  + e.getClass() и любую кастомную информацию какую пожелаешь. На выходе это даёт типизацию сообщений об исключениях и позволяет на стороне фронта также типизированно обрабатывать ошибки API

2023-04-05 07:43 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
> Если сделать как рекомендовал в методе getReviewById можно будет избавится от блока try и делать проверку в сервисе через запроc по id.

Сомнительно, что +1 подключение к базе данных , порождающийся доп.запросом лучше нежели try/catch

2023-04-05 07:44 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(String.format("Ошибка: отзыв с id=%d не найден.", id));
> Пока не могу найти аргументов в пользу queryForObject, но как то лист создававть кажется излишне. Как другие думают?

На мой взгляд это "вкусовщина"

2023-04-05 07:49 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertFilmExists");
> Надо подумать. Это все таки ДАО класс, а сервисный метод тогда лучше в сервисе использовать.

да, в DAO должны быть только методы производящие манипуляции с БД, прочие действия должны производится на уровне сервисного класса
С Иваном согласен, если есть такой метод в FilmService, то добавь в свой ReviewService  поле private final FilmService   и проверь аннотацию @RequiredArgsConstructor, если она есть, тогда через авто-инъектицию ты будешь иметь доступ к методам FilmService. Если там этот метод private , сделай его protected

2023-04-05 07:51 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.debug("Добавлен новый отзыв");
> Логи, как понял, для себя дублировали, для удобства?) Кириллицу в коде лучше не использовать)

Да, потому что по стектрейсу, без "ползания" дебагом замучаешься искать проблему.  Добавляя в начало метода лог , можно как в книге прочитать прохождение запросом методов и понять до какой точки программы дошёл запрос перед тем , как выкинулось исключение

2023-04-05 08:19 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            existingReview = jdbcTemplate.queryForObject(sql, reviewMapper, id);
Думаю что то, где происходит ошибка, можно понять по логам будет, отдельный метод ради этого не стоит писать)

2023-04-05 08:19 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +        log.debug("/assertReviewExists");
Артем опечатался, через Service видимо, Евгений выше написал хорошо и подробно что можно сделать

2023-04-05 09:33 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/ReviewDbStorage.java
> +            throw new NotFoundException(
Вот что мне ответил мой ревьюер на похожую ситуацию: "Необходимо исправить: Для данного класса также стоит добавить явные проверки на то, существует ли пользователь в БД для методов addUserFriends, deleteUserFriends, getUserFriends и getCommonFriends. Также в первых двух методах отлавливается ексепшен и выкидывается NotFoundException, но Exception не всегда означает, что данных нет в БД, иногда это может быть SQL ошибка или ошибка подключения к БД. Поэтому так делать не стоит".

2023-04-05 09:51 UTC, Fenris06 approved these changes

2023-04-05 09:53 UTC, Cheshire-Cat74 approved these changes

2023-04-05 10:57 UTC, Ivan-Mol approved these changes
Отличная работа!

2023-04-05 11:04 UTC, villidilli approved these changes

2023-04-05 11:34 UTC, merged