Added the ability to get common films
Ivan-Mol/java-filmorate pull request #16
Opened 2023-04-01 16:13 UTC by Cheshire-Cat74

2023-04-02 01:11 UTC, villidilli approved these changes
вижу много правок старого кода и судя по всему с Иваном их вместе сделала, поэтому часть не стал сам ревьюить, т.к. нужно разбираться во всем коде да и смысла нет, если обсуждала с Иваном. Оставил несколько предложений-вариаций

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> -import org.springframework.web.bind.annotation.*;
По мнению моего ревьюера, когда становится много "импорта" (3 и более) из одного пакета лучше объединять под *

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(Long id, String name, String description, LocalDate releaseDate, int duration, Mpa mpa) {
Не совсем понял зачем конструктор отдельный...

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/mem/InMemoryUserStorage.java
> +import java.util.ArrayList;
на мой взгляд лучше под *

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/mem/InMemoryFilmStorage.java
> +import java.util.ArrayList;
аналогично, лучше под * , т.к. больше 3 импортом из 1 пакета

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/UserDbStorage.java
> -import java.util.*;
лучше оставить со * , т.к. 5 импортов из одного пакета

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +                "FROM FILMS f " +
Тут кстати можно было сделать так: 
1. К таблице фильмов , где юзер 1 присоедить через Inner join такую же таблицу но где юзер 2 , тем самым ты получишь пересекающиеся у них фильмы
2. Левым джойном присоединить count ( likes) 
3. Левым джойном присоединить недостающие поля 
4. Сделать order by по count(likes)

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/GenreDbStorage.java
Этот код не ревьюил, так как судя по всему ты с Иваном что-то правила в старой реализации ввиду каких-то проблем

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/MpaDbStorage.java
Тоже не ревьюил, т.к. видимо правки старой реализации

2023-04-02 01:11 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +@Builder
не понял зачем билдер, если у нас есть сеттеры

2023-04-02 07:09 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getCommonFilms(long userId, long friendId) {
Мне кажется в это методе имеет смысл добавить проверки не существование юзеров в базе.

2023-04-02 07:09 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +        long id = rs.getLong("ID");
Здесь получается еще один метод по получению фильма из базы данных. У Ивана уже есть метод getFilms. Мне кажется лучше переиспользовать его метод. Если не получалось сделать сортировка, то в getFilms нужно HashMap заменить на LInkedHashMfp и все заработает.

2023-04-02 08:59 UTC, Ivan-Mol reviewed
Про импорты написал в телеге, со всем остальным согласен с ребятами

2023-04-02 09:13 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +@Builder
Забыла удалить

2023-04-02 09:14 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getCommonFilms(long userId, long friendId) {
Пожалуй, да

2023-04-02 09:21 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +                "FROM FILMS f " +
Да, можно. Но мой запрос тоже работает, так что считаю вкусовщиной)

2023-04-02 09:49 UTC, Cheshire-Cat74 commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +        long id = rs.getLong("ID");
Пока не знаю, как сделать, т.к. getFilms Ивана не принимает на вход Long userId, Long friendId.  Думаю, что менять метод не целесообразно, т.к. он используется в нескольких местах, можно задеть другой функционал и поломать тесты

2023-04-02 21:48 UTC, villidilli commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +                "FROM FILMS f " +
без проблем! просто привёл альтернативный вариант, поэтому и заапрувил ПР

2023-04-03 10:42 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/db/FilmDbStorage.java
> +        long id = rs.getLong("ID");
getFilms принимает sql запрос в который уже подставлены все значения. Нужно в твой sql запрос подставить userId и friendId и его передать

2023-04-03 16:01 UTC, Fenris06 approved these changes

2023-04-03 16:03 UTC, Fenris06 commented
Все отлично. Апруфнул.

2023-04-03 16:21 UTC, Ivan-Mol requested changes
Все супер, но я бы предложил поправить кое-что.

2023-04-03 16:21 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@AllArgsConstructor
Кажется эти два больше не нужны)

2023-04-03 16:21 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        User user = checkUserExists(userId);
Здесь лучше использовать просто filmStorage.get(userId);

2023-04-03 16:21 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (Objects.nonNull(user) && Objects.nonNull(friend)) {
Проверка на ноль не нужна, там не может быть нуля)

2023-04-03 16:46 UTC, Ivan-Mol approved these changes

2023-04-03 16:47 UTC, merged