Add recommendations
Ivan-Mol/java-filmorate pull request #8
Opened 2023-03-29 16:04 UTC by villidilli

Фича: рекомендации фильмов

2023-03-29 17:20 UTC, Cheshire-Cat74 approved these changes

2023-03-30 09:56 UTC, Ivan-Mol requested changes

2023-03-30 09:56 UTC, Ivan-Mol commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, films, mpa, genres, film_genres, likes, friends CASCADE;
Пока, наверное, пусть будет, но когда будем в мейн все мержить уже, я бы убрал)

2023-03-30 09:56 UTC, Ivan-Mol commented on src/main/resources/data.sql
> +INSERT INTO genres (id, name)
```suggestion
MERGE INTO genres (id, name)
```

2023-03-30 09:56 UTC, Ivan-Mol commented on src/main/resources/data.sql
> +INSERT INTO mpa (id, name)
```suggestion
MERGE INTO mpa (id, name)
```

2023-03-30 09:56 UTC, Ivan-Mol commented on src/main/java/ru/yandex/practicum/filmorate/storages/UserStorage.java
> +
Либо я не понял, либо забыл зачем это здесь) В остальном все круто)

2023-03-30 10:36 UTC, Ivan-Mol approved these changes

2023-03-30 11:12 UTC, closed without merging